openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: A simple REST API for managing tasks using Express and MongoDB.

servers:
  - url: https://task-manager-api-z1x4.onrender.com/api/v1/tasks
    description: Production server (Render)
  - url: http://localhost:3000/api/v1/tasks
    description: Local development server


paths:
  /getall:
    get:
      summary: Get all tasks
      tags:
        - Tasks
      responses:
        '200':
          description: List of all tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

  /create:
    post:
      summary: Create a new task
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /get/{id}:
    get:
      summary: Get a task by ID
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal Server Error

  /update/{id}:
    patch:
      summary: Update a task
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal Server Error

  /delete/{id}:
    delete:
      summary: Delete a task
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task deleted successfully
        '404':
          description: Task not found
        '500':
          description: Internal Server Error

components:
  schemas:
    Task:
      type: object
      properties:
        _id:
          type: string
          example: 64af9a274ff2315b5f8c2de3
        name:
          type: string
          example: Complete project report
        completed:
          type: boolean
          example: false
        createdAt:
          type: string
          format: date-time
          example: 2025-07-11T10:00:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2025-07-11T11:00:00Z
    TaskInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Finish backend module
        completed:
          type: boolean
          example: true
